### ISSUE TITLE
Custom validation?

### ISSUE THREAD

**Issue by paglias** [hiddentao/robe#1]
`simple-mongo-schema` supports only a few validation options. Adding support for your own validation method is a must I think.

BTW, great project, I was looking for something simple and clean like this :)

**Comment by hiddentao** [comment]
Good idea, will be best to add this functionality into **simple-mongo-schema** and then it will automatically be available in Robe.

**Comment by hiddentao** [comment]
Am closing this, tracking in hiddentao/simple-mongo-schema#1
