### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by mallowigi** [hiddentao/robe#10]
I've tried to use your library as described in the examples but insofar I got an error saying that I cannot use yield outside of a generator function.

Can you provide examples of usage? Thanks.

**Comment by hiddentao** [comment]
You need to use a coroutine library like [co](http://github.com/tj/co). Example:

```js
co(function*() {
  return yield collection.findOne({
    score: {
      $gt: 20
    },
  });
})
  .then(function(doc) {
    // do something with it
  })
```

**Comment by hiddentao** [comment]
I built Robe mainly to work with [koa](https://github.com/koajs/koa) so typically I don't have to manually use `co` since I'm already using generator functions everywhere.

**Comment by hiddentao** [comment]
Thanks for bringing this up though, I've added better usage docs to the README now.

**Comment by mallowigi** [comment]
I'm also using koa, this is why i found it odd to run it inside coroutines. Can you provide an example of how to use it with koa?

**Comment by hiddentao** [comment]
```js
var koa = require('koa');
var app = module.exports = koa();

app.use(function *(){
  var db = yield Robe.connect(...);

  this.body = yield db.collection('collectionName').findOne({ _id: ... });
  this.type = 'json';
});

app.listen(3000);
```

**Comment by ppbntl19** [comment]
can we use robe with express?

**Comment by hiddentao** [comment]
You can as long as you are using node in Harmony/ES6 mode. Because Robe uses generators.

**Comment by ppbntl19** [comment]
I am using Node js - v0.12.7
In my app.js 
var Robe = require('robe');
this  gives  me  error.

robe/node_modules/robe/build/database.js:41
      value: function* oplog() {
                     ^
SyntaxError: Unexpected token *

**Comment by hiddentao** [comment]
With Node 0.12 you still need to enable Harmony features on the CLI, see
http://stackoverflow.com/questions/28663639/generator-functions-in-node-0-12


On 29/07/2015 14:20, Pooran Prakash wrote:
> I am using Node js - v0.12.7
> In my app.js
> var Robe = require('robe');
> this gives me error.
> 
> robe/node_modules/robe/build/database.js:41
> value: function* oplog() {
> ^
> SyntaxError: Unexpected token *
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hiddentao/robe/issues/10#issuecomment-125854092>.
> 

-- 
Ramesh Nair

Freelance Web Developer

www.hiddentao.com
www.github.com/hiddentao

**Comment by ppbntl19** [comment]
Thanks
I am running 
```
node -- harmony app.js

var db =  yield Robe.connect("mongourl
                ^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

do I have to use babel-node?

**Comment by hiddentao** [comment]
@ppbntl19 You need `var Robe = require('robe')` at the top.
